language: android
sudo: false
android:
  components:
    - tools
    - build-tools-25.0.3
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    # The BuildTools version used by your project
    #- build-tools-19.1.0

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25

jdk: oraclejdk8
os:
  - linux

before_install:
  - chmod +x gradlew

# whitelist
branches:
  only:
    - develop

script:
 - ./gradlew test
 - export HOCKEYAPP_TOKEN="f7774aa8c8fd44af9f9914e4c871a70e"
 - ./gradlew assembleDebug
 - >
    curl
    -F "status=2"
    -F "notify=1"
    -F "notes=Some new features and fixed bugs."
    -F "notes_type=0"
    -F "ipa=@app/build/outputs/apk/app-debug.apk"
    -H "X-HockeyAppToken: ${HOCKEYAPP_TOKEN}"
    https://rink.hockeyapp.net/api/2/apps/upload
