language: android
sudo: false
android:
  components:
    - tools
    - build-tools-25.0.3
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    # The BuildTools version used by your project
    #- build-tools-19.1.0

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25

jdk: oraclejdk8
os:
  - linux

before_install:
  - chmod +x gradlew

script: ./gradlew connectedAndroidTest